# Generated by Django 3.2.5 on 2021-07-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wansentialsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
