# Generated by Django 3.2.5 on 2021-07-29 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wansentialsapp', '0002_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default=datetime.datetime(2021, 7, 29, 19, 57, 30, 652850, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
